//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeTareas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestorDeTareasModelContainer : DbContext
    {
        public GestorDeTareasModelContainer()
            : base("name=GestorDeTareasModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tarea> TareaSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Comentario> ComentarioSet { get; set; }
        public virtual DbSet<Prioridad> PrioridadSet { get; set; }
        public virtual DbSet<Estado> EstadoSet { get; set; }
    }
}
